# Site settings
title: DIFFgraph
email: NOOB@diff.WTF
description: Graph in the pompatus of DIFF . . . Learn. Appreciate. UNDERSTAND.
twitter_username: DIFFversity
github_username:  DIFFgraph

# Build settings
markdown: kramdown
